### ISSUE TITLE
Client error: 429 Too Many Requests

### ISSUE THREAD

**Issue by alidehkhodaei** [salehhashemi1992/ai-commit-assistant#1]
Hello, I followed all the steps correctly to use the action, but unfortunately, I encountered an error message that reads "Client error: POST https://api.openai.com/v1/chat/completions resulted in a 429 Too Many Requests response".

I believe this error message is related to the rate limits of the API but i have recently created an API.

Thank you in advance.

**Comment by salehhashemi1992** [comment]
Thank you for reaching out and bringing this issue to our attention. 
That means your free trial of 18$ (of all accounts registered before April) expired, even if you haven't used API key once.

**Comment by alidehkhodaei** [comment]
Okay Thanks.
